    - name: Restart server
      command: shutdown -r now "Reboot triggered by Ansible"
      async: 0
      poll: 0
      ignore_errors: true
    - name: Wait for server to restart
      local_action:
        module: wait_for
        host: nfservers
          port=22
          delay=1
          timeout=300

    - name: Start and Enable VMware Tools
      service: name=vmware-tools-services state=started enabled=yes

